version: "3"


services:
  mysql:
    container_name: to-do-list-mysql
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: to_do_list_db
      MYSQL_ALLOW_EMPTY_PASSWORD: no
    
    volumes:
      - "db:/var/lib/mysql"


volumes:
  db: