spring:
    datasource:
        url: jdbc:mysql://localhost:3306/to_do_list_db
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update